### ISSUE TITLE
Parallel aggregation

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#11]
Right now it takes up to days to fill out the Elastic Search database based on a list of URLs.

We need to have the celery workers perform the job in parallel instead of serially. Therefore we would need one worker machine per url on the list. Ideally, the computing resources to do it in parallel and the ones to do it serially would be the same (or close enough).

This has to be done within the Cloud Foundry environment.

**Comment by ingenieroariel** [comment]
```
check aggregated running logs here: https://papertrailapp.com/events

[8:39] 
measuring efectivity because tasks does not fail and services and layers are being created/updated/checked by uploaded endpoint lists.

[8:42] 
dont know how measure eficiency, but CPU usage in each instance shows high use, what is good for this kind of tasks and papertrail celery logs are saying that is processing a lot of tasks, some in serial (networking tasks) and some in parallel (geo tasks)

[8:44] 
check_all_service is a periodic task that is running each 900 seconds according CF local settings.```

**Comment by ingenieroariel** [comment]
![screen shot 2016-05-02 at 10 24 21 am](https://cloud.githubusercontent.com/assets/54999/14958353/0eba8b40-1050-11e6-8716-19c09e65d3c5.png)

**Comment by panchicore** [comment]
how to run:
- `cf push -f cf/manifest.yml` will deploy 2 instances, 1 for web and 1 for celery.

have in mind:
- required bindings: rabbitmq and papertrail
- logs in papertrail are more accurate and quicker than `cf logs app --recent`, create an account request access to @ingenieroariel.

next steps:
- dont hack cf health-checks by starting a django dev server, instead of that lets install https://github.com/mher/flower to monitor the workers pool to run in `CF $port`, I will create this task for myself.

possible future problems:
- to make quicker `cf push`, build package is a fork where was deactivated the routine for re-installing entire site-packages, will require test in order to see if breaks something in the mid-long term.

**Comment by panchicore** [comment]
https://github.com/boundlessgeo/exchange-search/issues/22

**Comment by ingenieroariel** [comment]
Thanks a lot @panchicore, I'll assign this to @JorgeMartinezG so he can take care of deploying.

**Comment by ingenieroariel** [comment]
Deployed.
